<?xml version="1.0"?>
<robot name="four_wheel_car" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Define properties for reusability -->
  <xacro:property name="wheel_radius" value="0.2"/>
  <xacro:property name="wheel_width" value="0.1"/>
  <xacro:property name="body_length" value="1.5"/>
  <xacro:property name="body_width" value="1.0"/>
  <xacro:property name="body_height" value="0.3"/>
  <xacro:property name="wheel_offset_x" value="0.7"/>
  <xacro:property name="wheel_offset_y" value="0.55"/>
  <xacro:property name="wheel_z" value="0.1"/>

  <!-- Base Link -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0"
               iyy="0.1" iyz="0.0"
               izz="0.1"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Define a wheel macro with orientation -->
  <xacro:macro name="wheel" params="name x y">
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} ${wheel_z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>  <!-- Fix rotation axis to Y-axis -->
    </joint>

    <link name="${name}_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.5"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                 iyy="0.01" iyz="0.0"
                 izz="0.01"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/> <!-- Correct visual orientation -->
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/> <!-- Correct collision orientation -->
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- Create 4 wheels -->
  <xacro:wheel name="front_left_wheel" x="${wheel_offset_x}" y="${wheel_offset_y}"/>
  <xacro:wheel name="front_right_wheel" x="${wheel_offset_x}" y="-${wheel_offset_y}"/>
  <xacro:wheel name="rear_left_wheel" x="-${wheel_offset_x}" y="${wheel_offset_y}"/>
  <xacro:wheel name="rear_right_wheel" x="-${wheel_offset_x}" y="-${wheel_offset_y}"/>

  <!-- Transmission for ROS control -->
  <xacro:macro name="wheel_transmission" params="name">
    <transmission name="${name}_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_motor">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </actuator>
    </transmission>
  </xacro:macro>

  <!-- Add Transmissions -->
  <xacro:wheel_transmission name="front_left_wheel"/>
  <xacro:wheel_transmission name="front_right_wheel"/>
  <xacro:wheel_transmission name="rear_left_wheel"/>
  <xacro:wheel_transmission name="rear_right_wheel"/>

  <!-- Gazebo Plugins -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
  </gazebo>

</robot>
